modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/headlesshq/mc-runtime-test"
license = "MIT"

[[mods]]
modId = "mc_runtime_test"
version = "${version}"
displayName = "MC-Runtime-Test"
authors = "3arthqu4ke"
description = '''
    Run tests on the Minecraft client at runtime
'''

[[dependencies.mc_runtime_test]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.0,)"
ordering = "NONE"
side = "BOTH"
